accounts/urls.py
from django.urls import path
from .views import signup, login, logout, profile, edit_profile, follow_api, unfollow_api

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    # gives you your own profile
    path('profile/', profile, name='profile'),
    # gives you another user's profile
    path('profile/<int:user_id>/', profile, name='profile'),
    # edit your profile
    path('profile/edit/', edit_profile, name="edit_profile"),
    path('profile/follow/<int:profile_id>/', follow_api, name="follow_api"),
    path('profile/unfollow/<int:profile_id>/', unfollow_api, name="unfollow_api"),
]

quotes/urls.py
from django.urls import path
from .views import *

app_name = "quotes"

urlpatterns = [
    path('', index, name='index'),
    path('search/', search, name='search'),
    path('create/', create, name='create'),
    path('<slug>', detail, name='detail'),
]

zpa700/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from quotes.views import index as quotes_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', quotes_index, name='index'),
    path('quotes/', include('quotes.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


def avatar_uploader(instance, filename):
    return 'avatars/{0}__{1}'.format(instance.user.id, filename)


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, default='',
                            blank=True, help_text="your name")
    bio = models.TextField(blank=True, default='', help_text="about (( You ))")
    avatar = models.ImageField(
        blank=True, upload_to=avatar_uploader, help_text="your ugly face")
    following = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return self.name + ' : ' + self.user.username

accounts/forms.py
from django import forms

BootstrappedUsernameInput = forms.TextInput(
    attrs={'class': 'form-control', "placeholder": "username"}
)
BootstrappedPasswordInput = forms.PasswordInput(
    attrs={"class": "form-control", "placeholder": "password"}
)
BootstrappedTextArea = forms.Textarea(
    attrs={'class': 'form-control'}
)
BootstrappedTextInput = forms.TextInput(
    attrs={'class': 'form-control'}
)
BootstrappedFileUpload = forms.ClearableFileInput(attrs={"class":"custom-file-input"})


class SignupForm(forms.Form):
    username = forms.CharField(max_length=20, label="user name", required=True, widget=BootstrappedUsernameInput)
    password = forms.CharField(label="password", required=True, widget=BootstrappedPasswordInput)
    password2 = forms.CharField(label="password2", required=True, widget=BootstrappedPasswordInput)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, label="user name", required=True, widget=BootstrappedUsernameInput)
    password = forms.CharField(label="password", required=True, widget=BootstrappedPasswordInput)


class ProfileEditForm(forms.Form):
    name = forms.CharField(max_length=20, required=True, widget=BootstrappedTextInput)
    bio = forms.CharField(max_length=300, required=False, widget=BootstrappedTextArea)
    avatar = forms.ImageField(required=False, widget=BootstrappedFileUpload)

accounts/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect, render, reverse
from zpa700.helpers import err_page

from .forms import LoginForm, ProfileEditForm, SignupForm
from .models import Account


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password2 = form.cleaned_data["password2"]

            # manual validation that passwords are matched
            if password != password2:
                return err_page(request, "oops!, seems like you've entered mismatched passwords")

            # create a user with the given username
            user = User(username=username)
            user.save()
            # attach the password to the user
            user.set_password(password)
            user.save()
            # login the newly created user
            auth.login(request, user)
            return redirect(reverse('index'))
    else:
        form = SignupForm()
        return render(request, 'accounts/signup.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = auth.authenticate(username=username, password=password)
            if not user:
                return err_page(request, "SEEMS LIKE YOURE NOT A USER REALLY HMMMM")
            else:
                auth.login(request, user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    return redirect(reverse('index'))


@login_required(login_url='/accounts/login/')
def logout(request):
    auth.logout(request)
    return redirect(reverse('index'))


@login_required(login_url='/accounts/login/')
def profile(request, user_id=None):
    if(not user_id):
        # give me my own account
        try:
            user = request.user
            account = Account.objects.get(user__id=user.id)

            return render(request, 'accounts/profile.html', {
                "account": account,
                "can_edit": True,
            })
        except ObjectDoesNotExist:
            # the user doesn't have an account yet
            # so, we will create an account for him and
            # then redirect him to the account edit page
            account = Account(user=request.user)
            account.save()

            return redirect(reverse('accounts:edit_profile'))
    else:
        # give me some other user's account profile
        try:
            other_user = User.objects.get(pk=user_id)
            other_account = Account.objects.get(user__id=other_user.id)

            # determine if i already follow him or not
            my_account = Account.objects.get(user__id=request.user.id)
            my_follow_list = my_account.following.all()
            if other_account in my_follow_list:
                does_follow = True
            else:
                does_follow = False

            # my_follow_list = Account.objects.filter(following=my_account)

            return render(request, 'accounts/profile.html', {
                "account": other_account,
                "can_edit": False,
                "does_follow": does_follow
            })
        except ObjectDoesNotExist:
            return err_page(request, 'this user or his account don\'t exist')


@login_required(login_url='/accounts/login/')
def edit_profile(request):
    if request.method == 'GET':
        # user is trying to get to the profile edit page
        try:
            # get the logged in user and his account
            user = request.user
            account = Account.objects.get(user__id=user.id)
        except ObjectDoesNotExist:
            # this could throw an exception so we handle it here
            return err_page(request, 'this user/account doesn\'t exist')

        # we make a ProfileEditForm object and fill it
        # with previous profile data
        data = {
            "name": account.name,
            'bio': account.bio,
            'avatar': account.avatar,
        }
        form = ProfileEditForm(data)

        # we then pass this filled (bound) form to the profile_edit page
        return render(request, 'accounts/edit_profile.html', {
            "form": form
        })

    elif request.method == 'POST':
        # user is trying to post the profile edit form
        try:
            user = request.user
            account = Account.objects.get(user__id=user.id)
        except ObjectDoesNotExist:
            return err_page(request, 'this user/account doesn\'t exist')

        form = ProfileEditForm(request.POST, request.FILES)
        if form.is_valid():
            account.name = form.cleaned_data["name"]
            account.bio = form.cleaned_data["bio"]
            account.avatar = request.FILES.get("avatar", None)
            account.save()
        else:
            return err_page(request, "the form yo ass submitted aint valid doe")

        return redirect(reverse('accounts:profile', args=[user.id]))


@login_required(login_url='/accounts/login/')
def follow_api(request, profile_id=None):
    try:
        user = request.user
        account = Account.objects.get(user__id=user.id)
        target_account = Account.objects.get(pk=profile_id)
    except ObjectDoesNotExist:
        return err_page(request, 'this user/account doesn\'t exist')

    account.following.add(target_account)
    account.save()
    return redirect(reverse('accounts:profile', args=[target_account.user.id]))


@login_required(login_url='/accounts/login/')
def unfollow_api(request, profile_id=None):
    try:
        user = request.user
        account = Account.objects.get(user__id=user.id)
        target_account = Account.objects.get(pk=profile_id)
    except ObjectDoesNotExist:
        return err_page(request, 'this user/account doesn\'t exist')

    account.following.remove(target_account)
    account.save()
    return redirect(reverse('accounts:profile', args=[target_account.user.id]))

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %} 
{% block content %}

{% block title %} Y0 Pr0Fil3 Ed1t P4g3 {% endblock title %}

<div class="row">
    <!-- padding div -->
    <div class="col-lg-3"></div>

    <!-- main content div -->
    <div class="col-lg-6 card">
        <div class="card-body">
            <!-- main edit form -->
            <form method="POST" action="{% url 'accounts:edit_profile' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- name input -->
                <h5 class="card-title">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">{{ form.name.label }}</span>
                        </div>
                        {{ form.name }}
                    </div>
                </h5>

                <!-- username indicator -->
                <h6 class="card-subtitle mb-2 text-muted">
                    username: {{ request.user.username|default:"" }}
                </h6>

                <p class="card-text">
                    <!-- bio input -->
                    <div class="input-group">
                        <div class="input-group-prepend">
                        <span class="input-group-text">{{ form.bio.label }}</span>
                        </div>
                        {{ form.bio }}
                    </div>

                    <!-- avatar image upload input -->
                    <div class="input-group my-3">
                        <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupFileAddon01">{{ form.avatar.label }}</span>
                        </div>
                        <div class="custom-file">
                        {{ form.avatar }}
                        <label class="custom-file-label" for="inputGroupFile01">Choose Image</label>
                        </div>
                    </div>
                </p>
                
                <!-- submit button -->
                <input type="submit" class="btn btn-success" value="Edit">
            </form>
        </div>
    </div>

    <!-- padding div -->
    <div class="col-lg-3"></div>
</div>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %} 

{% block title %} Y0 Pr0Fil3 {% endblock title %}

{% block content %}

<div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">


    <div class="card" >
        <img 
          {% if account.avatar %}
          src="{{ account.avatar.url }}"
          {% else %}
          src="/static/img/default_avatar.jpeg"
          {% endif %}
          class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">{{ account.name|default:"" }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
            {{ account.user.username|default:"" }}
        </h6>
        <p class="card-text">
            {{ account.bio }}
        </p>
        {% if can_edit %}
            <a href="{% url 'accounts:edit_profile' %}" class="card-link btn btn-success">Edit</a>
        {% else %}
          {% if does_follow %}
              <a href="{% url 'accounts:unfollow_api' account.id %}" 
                 class="card-link btn btn-danger">Unfollow</a>
          {% else %}
              <a href="{% url 'accounts:follow_api' account.id %}" 
                 class="card-link btn btn-primary">Follow</a>
          {% endif %}
        {% endif %}
      </div>
    </div>


  </div>
  <div class="col-lg-3"></div>
</div>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %} Y0 s1Gnup p4g3 {% endblock title %}


{% block content %}
<h1>Hello 7mada</h1>

<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{form}}
<button type="submit">Sign up</button>
</form>
{% endblock %}