quotes/urls.py
from django.urls import path
from .views import *

app_name = "quotes"

urlpatterns = [
    path('', index, name='index'),
    path('search/', search, name='search'),
    path('create/', create, name='create'),
    path('<slug>', detail, name='detail'),
]

zpa700/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from quotes.views import index as quotes_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', quotes_index, name='index'),
    path('quotes/', include('quotes.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Account
from django_extensions.db.fields import AutoSlugField

def my_slugify_function(content):
    return content.replace(' ', '-').replace('/', '-').lower()

class Quote(models.Model):
    # main data
    title = models.CharField(max_length=100)
    # slug = models.SlugField(unique=True, allow_unicode=True)
    slug = AutoSlugField(populate_from='title', slugify_function=my_slugify_function)
    body = models.TextField(max_length=400)
    author = models.ForeignKey(Account, null=True, on_delete=models.SET_NULL)
    image = models.ImageField(blank=True)
    # meta data
    date_added = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

quotes/forms.py
from django.forms import ModelForm
from .import models

class createQuote(ModelForm):
    class Meta:
        model = models.Quote
        fields = [ 'title', 'body', 'image' ]

quotes/views.py
from django.shortcuts import render,redirect
from .models import Quote
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .forms import *
from django.utils.text import slugify

def index(request):
    quotes = Quote.objects.all().order_by('date_added')
    paginator = Paginator(quotes, 7)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,"quotes/quotes-list.html",{'page_obj': page_obj})

def detail(request, slug):
    quote = Quote.objects.get(slug=slug)
    return render(request, 'quotes/quote-detail.html',{'Quote': quote})

def search(request):
    pass

@login_required(login_url='/accounts/login/')
def create(request):
    if request.method == 'POST':
        form = createQuote(request.POST, request.FILES)
        if form.is_valid():
            new_qt =  Quote(
                title = form.cleaned_data['title'],
                body = form.cleaned_data['body'],
                image = form.cleaned_data['image'],
            )
            new_qt.save()
            return redirect('index')
    else:
        form = createQuote()
    return render(request, 'quotes/quotes-create.html', {'form':form})

quotes/templates/quotes/quote-detail.html
{% extends 'base.html' %} 
{% block content %}

<div class="quote">
  <h3 class="quote-title">{{ Quote.title }}</h3>
  <p class="quote-detail">{{ Quote.body }}</p>
  <p class="author">{{ Quote.author }}</p>
  {% if Quote.image.url != null  %}
  <img class="quote-image" src="{{ Quote.image.url }}" alt="mza200 - image is buggy :("/>
  {% endif %}
  <p class="date">{{ Quote.date_added }}</p>
  </div>

{% endblock %}

quotes/templates/quotes/quotes-create.html
{% extends 'base.html' %} 
{% block content %}

<div class="create-quote">
    <h2>Post a awesome new Quote</h2>
    <form action="{% url 'quotes:create' %}" class="site-form" method="POST" enctype="multipart/form-data" class="form-group" onsubmit="myFunction()">
        {% load crispy_forms_tags %}
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Post Quote</button>
    </form>
    <p id="text"></p>
</div>

{% endblock %}

quotes/templates/quotes/quotes-list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Menawar ya king</h1>
    <li>Quotes list</li>
    <br>
    <div class="quotes">
        {% for Quote in page_obj %}
        <ul>
            <div class="quote">
                <a href="{% url 'quotes:detail' slug=Quote.slug %}"> {{ Quote.title }}</a>
                <p class="quote-detail">{{ Quote.body }}</p>
                <p class="author">{{ Quote.author }}</p>
                <p class="date">{{ Quote.date_added }}</p>
            </div>
        </ul>
        {% endfor %}
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>
</html>
{% endblock %}