accounts/urls.py
from django.urls import path
from .views import signup, login, logout, profile, edit_profile, follow_api, unfollow_api

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    # gives you your own profile
    path('profile/', profile, name='profile'),
    # gives you another user's profile
    path('profile/<int:user_id>/', profile, name='profile'),
    # edit your profile
    path('profile/edit/', edit_profile, name="edit_profile"),
    path('profile/follow/<int:profile_id>/', follow_api, name="follow_api"),
    path('profile/unfollow/<int:profile_id>/', unfollow_api, name="unfollow_api"),
]

quotes/urls.py
from django.urls import path
from .views import *

app_name = "quotes"

urlpatterns = [
    path('', index, name='index'),
    path('search/', search, name='search'),
    path('create/', create, name='create'),
    path('<slug>', detail, name='detail'),
]

zpa700/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from quotes.views import index as quotes_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', quotes_index, name='index'),
    path('quotes/', include('quotes.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Quotes Database {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    {% block navbar %}
    {% include 'navbar.html' %} 
    {% endblock navbar %}
    <div class="container-sm my-4">
      {% block content %} 
      {% endblock content %}
    </div>
  </body>
  <script src="{% static 'js/jquery.slim.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</html>

templates/error_page.html
{% extends 'base.html' %}
{% block content %}
<h1>BIG ASS ERROR MESSAGE<h1>

<h6>{{ message }}</h6>
{% endblock %}

templates/navbar.html
<header class="navbar sticky-top navbar-expand-lg navbar-dark"
     style="background-color: #14114a"
>
  <a class="navbar-brand" href="{% url 'index'%}">Z4P4700 Quotes</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% block home_active %} {% endblock home_active %}">
        <a class="nav-link" href="{% url 'index'%}"
          >Home</a
        >
      </li>
      <li class="nav-item {% block create_active %} {% endblock create_active %}">
        <a class="nav-link" href="{% url 'quotes:create'%}">Create A Quote</a>
      </li>   
    </ul>

<ul class="navbar-nav ml-auto">
    <form class="form-inline my-2 my-lg-0" target="{% url 'quotes:search' %}" method="GET">
      <input
        class="form-control mr-sm-2"
        type="search"
        placeholder="Search Quotes"
      />
      <button class="btn btn-outline-success mx-1 my-sm-0" type="submit">
        Search
      </button>
    </form>

      {% if user.is_authenticated %}
        <!-- username and logout buttons -->
        <a type="button" class="btn btn-outline-primary mx-1 my-sm-0"
          href="{% url 'accounts:profile' %}">{{ request.user.username }}</a>
        
        <a type="button" class="btn btn-outline-danger mx-1 my-sm-0" 
          href="{% url 'accounts:logout' %}">Logout</a>
      {% else %}
        <!-- dropdown form -->
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
          role="button" data-toggle="dropdown">
          Login</a>
        <div class="dropdown-menu">
          <form class="px-4 py-3" method="POST" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            <div class="form-group">
              {{request.login_form.username.label}}
              {{request.login_form.username}}
            </div>
            <div class="form-group">
              {{request.login_form.password.label}}
              {{request.login_form.password}}
            </div>
            <button type="submit" class="btn btn-primary">Log In</button>
          </form>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign Up</a>
        </div>
      {% endif %}
      </ul>
  </div>
</header>